### ISSUE TITLE
Delete #1

### ISSUE THREAD

**Issue by BannedPlushez** [official-notfishvr/Lethal-Company-Mod-Menu#1]
How do you use this? as i cant seem to open any type of menu

**Comment by BannedPlushez** [comment]
I have bepinex and this and insert does nothing

**Comment by KnightHikari** [comment]
> I have bepinex and this and insert does nothing

I also cant seem to get this to work :(

**Comment by SirShadowShark** [comment]
Hi, I was able to get a working version, though I had to do some modification to the code, I also changed ESP colors so that enemies are highlighted in red text. Do not want to post a public download, (without permission from notfishvr) and am unsure how to do a pull request with my modification. Feel free to shoot my a DM in discord (same as my github username), atm there's a few bugs with ESP.

**Comment by official-notfishvr** [comment]
> Hi, I was able to get a working version, though I had to do some modification to the code, I also changed ESP colors so that enemies are highlighted in red text. Do not want to post a public download, (without permission from notfishvr) and am unsure how to do a pull request with my modification. Feel free to shoot my a DM in discord (same as my github username), atm there's a few bugs with ESP.

you can post it

**Comment by SuperSybroBoy** [comment]
wheres the insert key on a 60% keyboard

**Comment by KirstenTheFolf** [comment]
@SirShadowShark please post the fix it isnt working for me either

**Comment by SirShadowShark** [comment]
@KirstenTheFolf https://github.com/SirShadowShark/LCMM Posted here, just download the DLL. Will make it prettier later. New activation key is F4.

**Comment by aeusyi** [comment]
@SirShadowShark are you on?

**Comment by SirShadowShark** [comment]
@aeusyi Yes, what's up?

**Comment by Mauyed** [comment]
the mod is not loading for some reason it just detect it
![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/45438191/4f6ec8f2-890f-42a9-8489-004afb1597ee)

**Comment by official-notfishvr** [comment]
its made for BepInEx

**Comment by Mauyed** [comment]
i got it to work already ty for awesome mod
