### ISSUE TITLE
Delete #10

### ISSUE THREAD

**Issue by MichaelDavidGK** [official-notfishvr/Lethal-Company-Mod-Menu#10]
Currently all ESP options seem to lag the game, consider objectCache and refreshInterval

XP is bugging in game, if you add too much XP it goes back from Boss to Intern in game, customisable field with XP amount or field/button with option to select add/remove would be nice

most of functions are still enabled after disabling them (ESP lags, Night Mode still on, etc)

consider making separate modules for every function and just call them from main file, it will make code much more readable

**Comment by Hacker1254** [comment]
seems like this mod was made by someone who compleatly understands c# right

**Comment by 11010Jackson** [comment]
How did you guys even open it? What is the keybinds and such?

**Comment by notfishvr6969** [comment]
> seems like this mod was made by someone who compleatly understands c# right

Yes why asking?

**Comment by Hacker1254** [comment]
why did you make it so bad then

**Comment by notfishvr6969** [comment]
> why did you make it so bad then

Wdym?

**Comment by Hacker1254** [comment]
you use serveral laggy resource grabs

**Comment by Hacker1254** [comment]
like in an Update

**Comment by notfishvr6969** [comment]
> you use serveral laggy resource grabs 

Then you make it 💀 I make stuff for fun

**Comment by Hacker1254** [comment]
this is the worse possible way you could've done this 
you have no clue how to code 
```
foreach (HDAdditionalLightData lightData in UnityEngine.Object.FindObjectsOfType<HDAdditionalLightData>())
                {
                    foreach (TimeOfDay timeOfDay in UnityEngine.Object.FindObjectsOfType<TimeOfDay>())
                    {
                        foreach (StartOfRound startOfRound in UnityEngine.Object.FindObjectsOfType<StartOfRound>())
                        {
                            lightData.lightDimmer = float.MaxValue;
                            lightData.distance = float.MaxValue;
                            timeOfDay.insideLighting = false;
                            startOfRound.blackSkyVolume.weight = 0;
                        }
                    }
                }
```

**Comment by notfishvr6969** [comment]
> like in an Update

My PC is broken

**Comment by Hacker1254** [comment]
it doesn't matter since you made it in the first place

**Comment by notfishvr6969** [comment]
> it doesn't matter since you made it in the first place

Ok I make stuff for FUN IDC if I made it bad that's how I code

**Comment by Hacker1254** [comment]
:|

**Comment by notfishvr6969** [comment]
> :|

?

**Comment by Hacker1254** [comment]
cringee removing the comments

**Comment by 11010Jackson** [comment]
God mode doesn't seem to work for me, as well as night-vision. Couple other buttons are bugged as well.

**Comment by IOnlyKnowGodot233** [comment]
How do you install the mod into the game I have no idea, the readme is so bad, please help

**Comment by notfishvr6969** [comment]
> How do you install the mod into the game I have no idea, the readme is so bad, please help

Readme is good wdym

**Comment by sword11247** [comment]
the boss to intern is a game bug going past 1500 will break the ranking system but there is a mod called rankfix which fixes this

**Comment by IOnlyKnowGodot233** [comment]
It is just telling me to insert the config.cfg, it mentions no where about
the dll file or the menu folders or even what key to press to open the mod
menu, I've replaced the config.cfg multiple times, inserted the dll file
and the menu folders In every place that is may fit, config, core, plugins
etc and then I don't know how to know if the mod is working because I don't
know what key(s) to press. Can you help?
