### ISSUE TITLE
Delete #11

### ISSUE THREAD

**Issue by 11010Jackson** [official-notfishvr/Lethal-Company-Mod-Menu#11]
How do I set it up, and use it? I downloaded the bepinex installer, launched it and it installed. But there isn't a config folder. Any specific instructions to help out?

**Comment by 11010Jackson** [comment]
I fixed it, turns out you have to load it then put it into the config file from there. New issue, what is the keybinds? How do I open the menu? Help?

**Comment by 11010Jackson** [comment]
I did NOT fix it. How do you even install this? All the useful issue forums were closed before I could ask, and the owner doesn't seem to respond on the discord.

**Comment by MissionApollo7** [comment]
> I did NOT fix it. How do you even install this? All the useful issue forums were closed before I could ask, and the owner doesn't seem to respond on the discord.

You may be using the wrong version of BepInEx. I was using a slightly outdated version of it, then I updated to 5.4.22.0 and the menu opened when I opened my game.

**Comment by notfishvr6969** [comment]
> I did NOT fix it. How do you even install this? All the useful issue forums were closed before I could ask, and the owner doesn't seem to respond on the discord.

My PC is broken
