### ISSUE TITLE
Delete #14

### ISSUE THREAD

**Issue by timyingus** [official-notfishvr/Lethal-Company-Mod-Menu#15]
The instructions don't specify how to install OR use the mod. Please fix this.

**Comment by notfishvr6969** [comment]
> The instructions don't specify how to install OR use the mod. Please fix this.

Then send me a msg I can Put. it's not ez when you have dumbass saying that but not telling me what to say

**Comment by kodam54** [comment]
![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/142541533/59a264f1-c678-4844-ab70-8f1b56632786)
![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/142541533/23563e80-91d9-4fe0-8558-00e816c4349e)
Am I wrong in the installation? I'm confused

**Comment by notfishvr6969** [comment]
> ![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/142541533/59a264f1-c678-4844-ab70-8f1b56632786)
> ![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/142541533/23563e80-91d9-4fe0-8558-00e816c4349e)
> Am I wrong in the installation? I'm confused
> The problem is that when I open the game there are no changes
> 

Can you read??

**Comment by yhngr** [comment]
How to install it ?? can you just answer ? I know your young but that's not a reason to look down on people who don't know how to install

**Comment by notfishvr6969** [comment]
> How to install it ?? can you just answer ? I know your young but that's not a reason to look down on people who don't know how to install 

I said my PC is broken more then 5 times and I'm not gonna help dumbass kids there's instructions

**Comment by wharisthisplace** [comment]
> > How to install it ?? can you just answer ? I know your young but that's not a reason to look down on people who don't know how to install
> 
> I said my PC is broken more then 5 times and I'm not gonna help dumbass kids there's instructions

My brother in christ, you specified how to install BepInEx, and not how to isntall your mod, maybe instead of calling everyone a dumbass you could say where to put these damn folders
created an account just to say this

**Comment by WasntCat** [comment]
the kid is a paster, he doesnt understand anything XD, but all you have to do is go into the bep config and change
HideManagerGameObject to true and save

**Comment by wharisthisplace** [comment]
> the kid is a paster, he doesnt understand anything XD, but all you have to do is go into the bep config and change HideManagerGameObject to true and save

did that, now what? nothing changed
