### ISSUE TITLE
Delete #2

### ISSUE THREAD

**Issue by jezbud** [official-notfishvr/Lethal-Company-Mod-Menu#2]
Installed bepinex and added this to plugins, Menu does not load

**Comment by KnightHikari** [comment]
add me on discord and I can help you. knight_hikari

**Comment by SirShadowShark** [comment]
@SuperSybroBoy @jezbud Posted a working DLL version @ https://github.com/SirShadowShark/LCMM , just download the DLL :)

**Comment by official-notfishvr** [comment]
@SirShadowShark say i made it in the github

**Comment by SirShadowShark** [comment]
> @SirShadowShark say i made it in the github

I did. Forgot to edit the readme when I first uploaded.

**Comment by official-notfishvr** [comment]
@SirShadowShark  ty

**Comment by SirShadowShark** [comment]
np, thanks for making it!
