### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by 13MrBlackCat13** [official-notfishvr/Lethal-Company-Mod-Menu#23]
Can you add the feature to change the hotkey?

**Comment by Sky420High** [comment]
he's pc broke theres not going too be any updates for this

**Comment by KreamyKappuccino** [comment]
what is the key for open the menu MOD ?

**Comment by 13MrBlackCat13** [comment]
> what is the key for open the menu MOD ?

insert

**Comment by KreamyKappuccino** [comment]
> > what is the key for open the menu MOD ?
> 
> insert

thx u . and my fps drop when the mod is activated . is it normal ?

**Comment by Helperbotguy** [comment]
im pressing insert but its not working.

**Comment by Helperbotguy** [comment]
and i have everything installed right

**Comment by Helperbotguy** [comment]
> > what is the key for open the menu MOD ?
> 
> insert

I have it in my plugins folder but its not opening up when i press insert

**Comment by notfishvr6969** [comment]
> > > what is the key for open the menu MOD ?
> > 
> > insert
> 
> I have it in my plugins folder but its not opening up when i press insert

READ ITS THAT EZ READ redo everything

**Comment by Sky420High** [comment]
You can find a better one on nexus it's called "PDKMODMENU" so far 10/10

**Comment by notfishvr6969** [comment]
> You can find a better one on nexus it's called "PDKMODMENU" so far 10/10

My boy IDC if it's good or not I make mods for fun and my PC is broken Soo I can't update it

**Comment by Helperbotguy** [comment]
not fish vr i already tried that and btw sky420high tysm for the info ima download that instead

**Comment by Sky420High** [comment]
Notfishvr so do I lol so your point is?? All I see is you keep saying pc is broke smh lol fix then bc I also build pc's for fun 🤣

**Comment by Sky420High** [comment]
Helperbotguy add me on discord @ Sky420High559

**Comment by Helperbotguy** [comment]
hey sky420high

**Comment by Helperbotguy** [comment]
k

**Comment by KreamyKappuccino** [comment]
> You can find a better one on nexus it's called "PDKMODMENU" so far 10/10

thx . but i used thunderstore mod manager and how to used it wih manager ?
