### ISSUE TITLE
bepinex.cfg not working

### ISSUE THREAD

**Issue by flamgo124** [official-notfishvr/Lethal-Company-Mod-Menu#25]
Whenever I click on **[BepInEx.cfg](https://notfishvr.dev/cdn/BepInEx.cfg)** it wont download and its like trying to go a deleted website. It just doesnt work.

**Comment by flamgo124** [comment]
(it times out basically)

**Comment by Helperbotguy** [comment]
flamgo

**Comment by Helperbotguy** [comment]
i had the same problem, but appearently the mod just straight up doesnt work. So instead use this https://www.nexusmods.com/lethalcompany/mods/110. also the owner is rude
