### ISSUE TITLE
bro what the fuck

### ISSUE THREAD

**Issue by sodaduhking** [official-notfishvr/Lethal-Company-Mod-Menu#27]
A

**Comment by cewlay** [comment]
How?

**Comment by cewlay** [comment]
What does it do?

**Comment by squishy9876** [comment]
its not a virus. open the project up in ILspy or Dnspy and check for yourself. this does exactly what it was meant to do.

another day another W for daddy fish

**Comment by squishy9876** [comment]
![image](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/89873236/73c59f1e-c603-4f7a-8939-c1c1676c3f09)

**Comment by goofidesgilb** [comment]
how do i open the mod menu i might be dumb

**Comment by IMrcat** [comment]
# Pasted Mess !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (:

**Comment by goofidesgilb** [comment]
> # Pasted Mess !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (:

what
