### ISSUE TITLE
GUI text on buttons not appearing

### ISSUE THREAD

**Issue by cluzier** [official-notfishvr/Lethal-Company-Mod-Menu#29]
As the title says, the GUI is not showing text, I am only able to see the buttons. When clicking them they work but since I am unable to see which option I am choosing it is very hard to determine which buttons to click.

See image attached:

![Screenshot 2024-01-14 at 9 36 59 PM](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/37819611/85e51873-9f70-4f7c-951a-3f0200457b88)

**Comment by notfishvr6969** [comment]
> As the title says, the GUI is not showing text, I am only able to see the buttons. When clicking them they work but since I am unable to see which option I am choosing it is very hard to determine which buttons to click.
> 
> See image attached:
> 
> ![Screenshot 2024-01-14 at 9 36 59 PM](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/37819611/85e51873-9f70-4f7c-951a-3f0200457b88)
> 

Redownload the game and the file

**Comment by cluzier** [comment]
> > As the title says, the GUI is not showing text, I am only able to see the buttons. When clicking them they work but since I am unable to see which option I am choosing it is very hard to determine which buttons to click.
> > 
> > See image attached:
> > 
> > ![Screenshot 2024-01-14 at 9 36 59 PM](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/37819611/85e51873-9f70-4f7c-951a-3f0200457b88)
> > 
> 
> Redownload the game and the file

I've tried reinstalling the game and file with no luck.

I am playing LC using Whisky since I am on a MacBook Pro. Maybe there is an issue with fonts?
