### ISSUE TITLE
Delete #3

### ISSUE THREAD

**Issue by 5Grn** [official-notfishvr/Lethal-Company-Mod-Menu#3]
I have bepinEx and the mod menu installed, but when I press insert nothing happens. Does v2 not work or smt

**Comment by SuperSybroBoy** [comment]
> add me on discord and I can help. knight_hikari

added

**Comment by KnightHikari** [comment]
> What is a fix for menu not showing up? whats the keybind?

if it's not showing up you installed the bepinex incorrectly, you can add me and I can help you set it up 
my discord is knight_hikari

**Comment by 11010Jackson** [comment]
Hikari, I added you. I would appreciate help

**Comment by 11010Jackson** [comment]
@KnightHikari
