### ISSUE TITLE
Delete #4

### ISSUE THREAD

**Issue by ToaruRailgun** [official-notfishvr/Lethal-Company-Mod-Menu#4]
afew of the unworking modules include

god-mode
fly
speed (it only has 1 speed settings, and cannot be disabled, nor slowed down or sped up)
night vision

there are some other things, im just listing the ones myself and i think most other people would like to see working again

**Comment by official-notfishvr** [comment]
fly works

**Comment by Mqnga** [comment]
> fly works

If you fly in multiplayer, you bug out, you cant see people around you, and sometimes it sticks you in the floor too and you cant move

Ill record a video or something later

**Comment by Mqnga** [comment]
> If you fly in multiplayer, you bug out, you cant see people around you, and sometimes it sticks you in the floor too and you cant move

i want to correct this statement*
it was conflicting with an outdated mod i had (now updated) and works fine, altho flying seems to toggle no clip (not sure if this is intended)

rest of the list doesnt work, along with afew other modules

**Comment by DestinedLight** [comment]
I also had an issue with speed not working with it's slider and constantly being too fast, add money doesn't add money, but add 100k acts as a toggle and just throws millions in an instant...

**Comment by armorfid** [comment]
"Set Level High" is not a very good name, it should be renamed "Add Player XP"

Also now I'm stuck with 500,000 XP, my rank is totally bugged and it won't go past Intern
