### ISSUE TITLE
Delete #6

### ISSUE THREAD

**Issue by LunarisFP** [official-notfishvr/Lethal-Company-Mod-Menu#6]
While using the mod my pc lags entirely and it is almost unplayable. Would it be possible to making some optimization update?

**Comment by plem62** [comment]
i second this, i have the same issue

**Comment by plem62** [comment]
using BepinEx Pack, i get errors such as this

>

>  [Warning: Unity Log] [Dissonance:Recording] (09:19:59.825) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:19:59.953) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:20:00.066) BasePreprocessingPipeline: Lost 1920 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:20:00.159) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:20:00.317) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:20:00.435) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate
> [Warning: Unity Log] [Dissonance:Recording] (09:20:00.583) BasePreprocessingPipeline: Lost 3840 samples in the preprocessor (buffer full), injecting silence to compensate

**Comment by loayerer** [comment]
owner of this said he doesnt care

**Comment by official-notfishvr** [comment]
? @loayerer

**Comment by ScorchinOrphan** [comment]
![Screenshot 2023-12-11 205543](https://github.com/official-notfishvr/Lethal-Company-Mod-Menu/assets/153575430/2607dc86-b4aa-4770-9cfb-080a7585b011)

Comment?

**Comment by official-notfishvr** [comment]
ITS FUCKING OPEN SRC

**Comment by ScorchinOrphan** [comment]
> ITS FUCKING OPEN SRC

Guy, you act like I should have any fucking idea what that means past its available for people able to read this shit openly, I just put shit through scans because thats a common fucking security practice, and when I see 3 Trojan flags I wonder whats going on. Your failure to even attempt to explain what it is and hiding behind "Learn code and search through the entire compiled info while also learning what to look out for with trojans" tells me its not worth my time looking for an answer because youre avoiding any sort of answer to the guys who are suddenly having their entire rigs slow down when the game runs now, so you are incapable of explaining the issues or hiding something. All I needed to know.

**Comment by official-notfishvr** [comment]
1. its open src  (soo you can see the code 💀 )
2. why use virustotal it sucks
3. if it was a virus github would of removed it
4. stop useing chatgpt 💀

**Comment by ScorchinOrphan** [comment]
Chat GPT? Youre actually a bot. I know its open code so I can see. Thanks for being incapable of explaing the issues people are having and hiding behind "You should be able to do it yourself" Actually pathetic specimen.

**Comment by official-notfishvr** [comment]
still Chat GPT and pls stop using big words and its open src not open code 🤡

**Comment by ScorchinOrphan** [comment]
Dude, my guy, hang yourself. Cant explain why your shit is mysteriously slowing people down and has flags. Adios, Should have known Github script kids wouldnt be able to explain the things they claim to make and would hide behind "Youre a.i.". Legit a strat used by scam artists and people caught in bullshit now. Please die, thank you.

**Comment by ScorchinOrphan** [comment]
Lt mi simpfly my txts to your brended mnd since typoing too wel lokjs likme a bot to retawds tlike you.

**Comment by official-notfishvr** [comment]
first I'm 13 and still using chatgpt and where's the proof I skid????????? and wdym "slowing people down and has flags" its a game hack its goanna have "flags"

**Comment by winstxnhdw** [comment]
Hey @LunarisFP,

My friend and I are actively maintaining [lc-hax](https://github.com/winstxnhdw/lc-hax).  It has some of the features here and more, and it is thoroughly optimised for performance. It also doesn't require host privileges.
