### ISSUE TITLE
Delete #9

### ISSUE THREAD

**Issue by Doddik911** [official-notfishvr/Lethal-Company-Mod-Menu#9]
i just cant set it up im useing  thunderstore mod manger idk if that has anything to do with it but i do ha bepinex installed

**Comment by Psaurin** [comment]
love how the asshole creator just ignores everything because it's probably malitious

**Comment by notfishvr6969** [comment]
> love how the asshole creator just ignores everything because it's probably malitious

MY PC IS FUCKING BROKEN

**Comment by notfishvr6969** [comment]
> love how the asshole creator just ignores everything because it's probably malitious

And how is it malitious bc I'm not helping you???? My pc is broken but still if it was not I still would not help but there's installment guides it literally says retry it if you have a problem
